default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: libify
  password: GikvSmZBn3DeGAQGI8bhh1QJVLNzR2ev

development:
  <<: *default
  database: libify

test:
  <<: *default
  database: libify

production:
  <<: *default
  database: libify